
services:
  postgres:
    image: postgres:16
    container_name: freerecipe_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: freerecipe
      POSTGRES_USER: freerecipe_user
      POSTGRES_PASSWORD: freerecipe_password
    ports:
      - "5432:5432"
    volumes:
      - freerecipe_pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./API
    container_name: freerecipe_backend
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=freerecipe;Username=freerecipe_user;Password=freerecipe_password
    ports:
      - "5000:80"

  frontend:
    build:
      context: ./frontend
    container_name: freerecipe_frontend
    ports:
      - "4200:4200"
    command: ["npm", "start"]
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  freerecipe_pgdata: