services:
  postgres:
    image: postgres:16
    container_name: freerecipe_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: freerecipe
      POSTGRES_USER: freerecipe_dev
      POSTGRES_PASSWORD: freerecipe_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: